name: Unzip and Upload

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  unzip_upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Download zip file
      run: |
        echo "Starting download..."
        wget http://kjv.wordfree.net/bibles/app/audio/1.zip -O 1.zip
        echo "Download completed."

    - name: Verify download
      run: |
        if [ -f "1.zip" ]; then
          echo "File downloaded successfully."
        else
          echo "File download failed."
          exit 1
        fi

    - name: Unzip file
      run: |
        echo "Unzipping file..."
        unzip 1.zip -d KJV
        echo "Unzipping completed."

    - name: List contents of KJV folder
      run: |
        echo "Contents of KJV folder:"
        ls Gen

    - name: Configure git
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

    - name: Add changes to git
      run: git add .

    - name: Commit changes
      run: git commit -m 'Add unzipped files to KJV folder'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
